from typing import TypedDict,Annotated,List,Dict,Any
from langgraph.graph.message import add_messages

class AgentState(TypedDict):
    ticker:str

    # Raw data fetched by MCP server
    market_data: Dict[str, Any]

    financial_statements:Dict[str,Any]
    # Reports generated by specific Agents
    fundamental_analysis:str
    technical_analysis:str

    # the final inveestment memo
    final_memo:str

    # Chat/agent messages history
    messages: Annotated[List[Any], add_messages]
    # Track which agent is currently active or next in line
    next_agent: str
    